### ISSUE TITLE
Standalone code for OSLO

### ISSUE THREAD

**Issue by kshitijd20** [ebennequin/few-shot-open-set#3]
Thanks for sharing the code.
If I want to test OSLO on some query and support features how can I do a standalone inference using OSLO from this code?

**Comment by ebennequin** [comment]
Hi, sorry for the delay! You can find the inference code for OSLO [here](https://github.com/ebennequin/few-shot-open-set/blob/master/src/all_in_one/osem.py).

**Comment by kshitijd20** [comment]
Thanks 👍
