### ISSUE TITLE
Request to add license 

### ISSUE THREAD

**Issue by kshitijd20** [ebennequin/few-shot-open-set#4]
Thanks for the interesting paper and sharing the source code. I find OSLO method quite relevant to a project I am working on and therefore I am interested in exploring it. 

I noticed the repository at the moment does not have a license. Therefore, I request you to kindly add a license to the repository.

Adding a license will provide clarity to users about the permissions and restrictions associated with the usage of this repository.

**Comment by ebennequin** [comment]
Hi, thanks for raising this issue, we're discussing it with our respective organizations and we'll add a license shortly.

**Comment by ebennequin** [comment]
Added an MIT license!

**Comment by kshitijd20** [comment]
Great thanks 👍
